server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost:4200"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          # Ce filtre est important pour que le microservice reçoive le bon chemin
          filters:
            - RewritePath=/api/auth/(?<path>.*), /$\{path}

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/boards/**
          filters:
            - RewritePath=/api/boards/(?<path>.*), /$\{path}
springdoc:
  swagger-ui:
    urls:
      # On aligne les URLs sur les predicates Path définis plus haut
      - name: Auth Service
        url: /api/auth/v3/api-docs
      - name: Board Service
        url: /api/boards/v3/api-docs

eureka:
  client:
    service-url:
      # Rappel : utilise discovery-service si tu lances via Docker
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
