services:
  postgres-auth:
    image: postgres:16-alpine
    container_name: kanban-db-auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_AUTH_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data:
